The script pullinitialsitefromsource has been made more generic and helper files have been added.

diff --git a/pullinitialsitefromsource b/pullinitialsitefromsource
--- a/pullinitialsitefromsource
+++ b/pullinitialsitefromsource
@@ -11,7 +11,8 @@
 # Logging setup
 # -------------------------------------------------------------------------------------------------
 
-# These lines have been copied from http://stackoverflow.com/questions/3173131/redirect-copy-of-stdout-to-log-file-from-within-bash-script-itself
+# These lines have been copied from 
+# http://stackoverflow.com/questions/3173131/redirect-copy-of-stdout-to-log-file-from-within-bash-script-itself
 # and will send the script output to a log file.
 mkdir -p ~/logs/pullpush
 DATE_TIME=`date +%Y%m%d-%H%M%S`
@@ -52,39 +53,15 @@ fi
 
 
 # Todo
-# Here we need to check that the intial site name has not been used already.
+# Here we need to check that the intial site name has not been used already and is 
+# valid.
 
 
-
-
-## # Check the variables file exists.
-## if [ -e ~/.pullpush/${1} ]
-## then
-##        source ~/.pullpush/$1
-## else
-##        echo "ERROR - Configuration file $1 not found."
-##        exit -1
-## fi
-
-## # Check the global settings file exists.
-## if [ -e /home/pullpush/.pullpush/projects/${1} ]
-## then
-##        source /home/pullpush/.pullpush/projects/${1}
-## else
-##        echo "ERROR - Global configuration file $1 not found."
-##        exit -1
-## fi
-
-# NB - Here we need to check the branch name is short and that
-# it is unique.
+source /etc/pullpush.conf
 
 DATE_TIME=`date +%Y%m%d-%H%M%S`
 PROJECT_TYPE=${1}
 INITIAL_SITE_NAME=${2}
-
-
-# =================================
-
 
 # -------------------------------------------------------------------------------------------------
 echo
@@ -97,58 +74,81 @@ echo "Create database name, user name and password..."
 # has a limit on database usernames of 16 characters.
 # NB - It would be good to put hyphens inbetween the parts of the database name but 
 # this causes problems with MySQL.
-DATABASE_NAME=${USER}${PROJECT_TYPE}${INITIAL_SITE_NAME}
+DATABASE_NAME=${USER}${INITIAL_SITE_NAME}
 DATABASE_USER=`cat /dev/urandom | base64 | tr -d '[:punct:]' | tr -d '[:digit:]' | tr -d '[:upper:]' | cut -c1-10 | head -1`
 DATABASE_PASSWORD=`cat /dev/urandom | base64 | tr -d '[:punct:]' | tr -d '[:digit:]' | tr -d '[:upper:]' | cut -c1-10 | head -1`
+
+# Todo
+# Need to check that the database name or database username has not been used already.
+
+# We do this first to make sure the document root exists - otherwise the 'rcapache2 restart' command
+# will produce a warning.
+mkdir -p ~/initial_sites
 
 # -------------------------------------------------------------------------------------------------
 echo
 echo `date`
-echo "Download Drupal site..."
+echo "Download site files..."
 # -------------------------------------------------------------------------------------------------
+case "${PROJECT_TYPE}" in
 
-# We do this first to make sure the document root exists - otherwise the 'rcapache2 restart' command
-# will produce a warning.
-# mkdir -p ~/projects/${PROJECTS_NAME}/branches
-mkdir -p ~/initial_sites
-cd ~/initial_sites
-
-
-drush dl drupal-7 --drupal-project-rename=${INITIAL_SITE_NAME}
-
-case "$1" in
     drupal7)
-        echo "This will dl a d7 site."
+	echo
+	echo `date`
+	echo "Download a Drupal 7 site..."
+        drush dl drupal-7 --drupal-project-rename=${INITIAL_SITE_NAME} --destination=/home/${USER}/initial_sites
         ;;
     
     drupal6)
-        echo "This will dl a d6 site."
+	echo
+	echo `date`
+	echo "Download a Drupal 6 site..."
+        drush dl drupal-6 --drupal-project-rename=${INITIAL_SITE_NAME} --destination=/home/${USER}/initial_sites
         ;;
     
-    symfony)
-        echo "This will dl a d6 site."
-        ;;
     *)
         echo "Error - Invalid project type."
         exit 1
 esac
 
-
-
-
 # -------------------------------------------------------------------------------------------------
 echo
 echo `date`
-echo "Create web space for the branch site..."
+echo "Set up the vhost for the site..."
 # -------------------------------------------------------------------------------------------------
+case "$SERVER_TYPE" in
 
-sudo cp /etc/apache2/vhosts.d/vhost-drupal.template /etc/apache2/vhosts.d/${USER}-${PROJECT_TYPE}-${INITIAL_SITE_NAME}.dev3.conf
+    debian)
+	echo
+	echo `date`
+        echo "Set up vhost on Debian."
+        sudo cp /usr/share/local/pullpush/vhost-drupal7.template /etc/apache2/sites-available/${USER}-initial-site-${INITIAL_SITE_NAME}
 
-# Modify the template file.
-sudo sed -i "s/username/${USER}/g" /etc/apache2/vhosts.d/${USER}-${PROJECT_TYPE}-${INITIAL_SITE_NAME}.dev3.conf
-sudo sed -i "s/projectname/${PROJECT_TYPE}/g" /etc/apache2/vhosts.d/${USER}-${PROJECT_TYPE}-${INITIAL_SITE_NAME}.dev3.conf
-sudo sed -i "s/branchname/${INITIAL_SITE_NAME}/g" /etc/apache2/vhosts.d/${USER}-${PROJECT_TYPE}-${INITIAL_SITE_NAME}.dev3.conf
-sudo /usr/sbin/rcapache2 restart
+        sudo sed -i "s/username/${USER}/g" /etc/apache2/vhosts.d/${USER}-initial-site-${INITIAL_SITE_NAME}
+        sudo sed -i "s/initialsitename/${INITIAL_SITE_NAME}/g" /etc/apache2/vhosts.d/${USER}-initial-site-${INITIAL_SITE_NAME}
+        sudo sed -i "s/serverfqdn/${SERVER_FQDN}/g" /etc/apache2/vhosts.d/${USER}-initial-site-${INITIAL_SITE_NAME}
+        sudo sed -i "s/serveradminemail/${SERVER_ADMIN_EMAIL}/g" /etc/apache2/vhosts.d/${USER}-initial-site-${INITIAL_SITE_NAME}
+
+        sudo a2ensite ${USER}-initial-site-${INITIAL_SITE_NAME}
+        sudo apache2ctl restart
+        ;;
+    
+    sles)
+        echo "Set up a vhost on SLES."
+        sudo cp /etc/apache2/vhosts.d/vhost-drupal7.template /etc/apache2/vhosts.d/${USER}-initial-site-${INITIAL_SITE_NAME}.conf
+
+        sudo sed -i "s/username/${USER}/g" /etc/apache2/vhosts.d/${USER}-initial-site-${INITIAL_SITE_NAME}.conf
+        sudo sed -i "s/initialsitename/${INITIAL_SITE_NAME}/g" /etc/apache2/vhosts.d/${USER}-initial-site-${INITIAL_SITE_NAME}.conf
+        sudo sed -i "s/serverfqdn/${SERVER_FQDN}/g" /etc/apache2/vhosts.d/${USER}-initial-site-${INITIAL_SITE_NAME}.conf
+        sudo sed -i "s/serveradminemail/${SERVER_ADMIN_EMAIL}/g" /etc/apache2/vhosts.d/${USER}-initial-site-${INITIAL_SITE_NAME}.conf
+
+        sudo /usr/sbin/rcapache2 restart
+        ;;
+
+    *)
+        echo "Error - Invalid server type."
+        exit 1
+esac
 
 # -------------------------------------------------------------------------------------------------
 echo
@@ -162,9 +162,37 @@ echo "Create the database for the site..."
 # NB - It is possible to run the 'drush site-install' command and specify the root user for MySQL - but this would expose the
 # MYSQL root user and password to anyone who can read this script - and this might include user accounts which are not in the 
 # wheel group.
+case "$PROJECT_TYPE" in
+    drupal7)
+        echo
+	echo `date`
+	echo "This will set up a database for a Drupal 7 site."
 
-sudo mysqladmin create ${DATABASE_NAME}
-sudo mysql --execute="GRANT ALL ON ${DATABASE_NAME}.* TO '${DATABASE_USER}'@'localhost' IDENTIFIED BY '${DATABASE_PASSWORD}';" ${DATABASE_NAME}
+        # NB - It is possible to run the 'drush site-install' command and specify the root user for MySQL - but this would expose the
+        # MYSQL root user and password to anyone who can read this script - and this might include user accounts which are not in the 
+        # wheel group.
+
+	sudo mysqladmin create ${DATABASE_NAME}
+	sudo mysql --execute="GRANT ALL ON ${DATABASE_NAME}.* TO '${DATABASE_USER}'@'localhost' IDENTIFIED BY '${DATABASE_PASSWORD}';" ${DATABASE_NAME}
+        ;;
+
+    drupal6)
+        echo
+	echo `date`
+	echo "Setting up a database for a Drupal 6 site..."
+
+        # NB - It is possible to run the 'drush site-install' command and specify the root user for MySQL - but this would expose the
+        # MYSQL root user and password to anyone who can read this script - and this might include user accounts which are not in the 
+        # wheel group.
+
+	sudo mysqladmin create ${DATABASE_NAME}
+	sudo mysql --execute="GRANT ALL ON ${DATABASE_NAME}.* TO '${DATABASE_USER}'@'localhost' IDENTIFIED BY '${DATABASE_PASSWORD}';" ${DATABASE_NAME}
+        ;;
+    
+    *)
+        echo "Error - Invalid project type."
+        exit 1
+esac
 
 # -------------------------------------------------------------------------------------------------
 echo
@@ -172,25 +200,68 @@ echo `date`
 echo "Carry out a site install on the new site based on the database just created..."
 # -------------------------------------------------------------------------------------------------
 
-cd ~/projects/${PROJECT_TYPE}/branches/${INITIAL_SITE_NAME}
-drush site-install standard --db-url=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@localhost/${DATABASE_NAME} --yes
+case "$PROJECT_TYPE" in
+    drupal7)
+	echo
+	echo `date`
+        echo "Carrying out a site install on the Drupal 7 site..."
 
-# Now we've allowed the user to set up the Drupal site we're going to reduce the user
-# down to only the rights which they need to run Drupal.  We do this by revoking all 
-# rights and then only allowing the required rights.
+	cd ~/initial_sites/${INITIAL_SITE_NAME}
+	drush site-install standard --db-url=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@localhost/${DATABASE_NAME} --yes
 
-sudo mysql --execute="REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${DATABASE_USER}'@'localhost' IDENTIFIED BY '${DATABASE_PASSWORD}';" ${DATABASE_NAME}
-sudo mysql --execute="GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON ${DATABASE_NAME}.* TO '${DATABASE_USER}'@'localhost' IDENTIFIED BY '${DATABASE_PASSWORD}';" ${DATABASE_NAME}
+        # Now we've allowed the user to set up the Drupal site we're going to reduce the user
+        # down to only the rights which they need to run Drupal.  We do this by revoking all 
+        # rights and then only allowing the required rights.
+	sudo mysql --execute="REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${DATABASE_USER}'@'localhost' IDENTIFIED BY '${DATABASE_PASSWORD}';" ${DATABASE_NAME}
+	sudo mysql --execute="GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON ${DATABASE_NAME}.* TO '${DATABASE_USER}'@'localhost' IDENTIFIED BY '${DATABASE_PASSWORD}';" ${DATABASE_NAME}
 
-echo "This is the URL for your new website:"
-echo ${USER}-${PROJECT_TYPE}-${INITIAL_SITE_NAME}.dev3
+	echo 
+	echo `date`
+	echo "THIS IS THE URL FOR THE NEW SITE: "
+	echo ${USER}-initial-sites-${INITIAL_SITE_NAME}.${SERVER_FQDN}
 
-# -------------------------------------------------------------------------------------------------
-echo
-echo `date`
-echo "Change permissions on the files directory to enable the web server to write to it..."
-# -------------------------------------------------------------------------------------------------
-sudo chmod 777 -R ~/projects/${PROJECT_TYPE}/branches/${INITIAL_SITE_NAME}/sites/default/files
+	if [ $APACHE_TYPE ne "ITK" ]
+	    then
+	    echo
+	    echo `date`
+	    echo "Setting permissions for the files/ directory for non-ITK sites so the web server can write to it..."
+	    sudo chmod 777 -R ~/projects/initial_sites/${INITIAL_SITE_NAME}/sites/default/files
+	fi
+        ;;
+    
+    drupal6)
+	echo
+	echo `date`
+        echo "Carrying out a site install on the Drupal 7 site..."
+
+	cd ~/initial_sites/${INITIAL_SITE_NAME}
+	drush site-install standard --db-url=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@localhost/${DATABASE_NAME} --yes
+
+        # Now we've allowed the user to set up the Drupal site we're going to reduce the user
+        # down to only the rights which they need to run Drupal.  We do this by revoking all 
+        # rights and then only allowing the required rights.
+	sudo mysql --execute="REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${DATABASE_USER}'@'localhost' IDENTIFIED BY '${DATABASE_PASSWORD}';" ${DATABASE_NAME}
+	sudo mysql --execute="GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON ${DATABASE_NAME}.* TO '${DATABASE_USER}'@'localhost' IDENTIFIED BY '${DATABASE_PASSWORD}';" ${DATABASE_NAME}
+
+	echo 
+	echo `date`
+	echo "THIS IS THE URL FOR THE NEW SITE: "
+	echo ${USER}-initial-sites-${INITIAL_SITE_NAME}.${SERVER_FQDN}
+
+	if [ $APACHE_TYPE ne "ITK" ]
+	    then
+	    echo
+	    echo `date`
+	    echo "Setting permissions for the files/ directory for non-ITK sites so the web server can write to it..."
+	    sudo chmod 777 -R ~/projects/initial_sites/${INITIAL_SITE_NAME}/sites/default/files
+	fi
+        ;;
+    
+    *)
+        echo "Error - Invalid project type."
+        exit 1
+esac
+
 
 # -------------------------------------------------------------------------------------------------
 echo
