Minor changes and tidy ups.  Sorted out permissions for non-ITK web server, added script locking, cache clearing and made backups generic to save server space being used up.

diff --git a/pulldevfrombeta b/pulldevfrombeta
--- a/pulldevfrombeta
+++ b/pulldevfrombeta
@@ -13,6 +13,13 @@
 # COMPANY: Freeway Projects Limited
 #===================================================================================
 
+# Make sure only one Pullpush script is running at any one time.
+exec 9>/var/lock/pullpush
+if ! flock -n 9  ; then
+   echo "Another Pullpush script is currently running - try again later.";
+   exit 1
+fi
+
 # -------------------------------------------------------------------------------------------------
 # Set up global variables.
 #
@@ -161,7 +168,7 @@ check_beta_files_into_svn () {
     echo "Creating a database copy with the matching revision number..."
     new_beta_revision=$(svn info /home/beta/projects/${PROJECT_NAME}/web | grep '^Revision:' | sed s/^Revision:[[:space:]]*// )
     sudo -u beta -i "mkdir -p /home/beta/backups"
-    sudo -u beta -i "cp /home/${USER}/backups/beta_sites/${PROJECT_NAME}_${DATE_TIME}.sql /home/beta/backups/${PROJECT_NAME}_r${new_beta_revision}.sql"
+    sudo -u beta -i "cp /home/${USER}/backups/beta_sites/${PROJECT_NAME}.sql /home/beta/backups/${PROJECT_NAME}_r${new_beta_revision}.sql"
 }
 
 # -------------------------------------------------------------------------------------------------
@@ -225,10 +232,26 @@ echo "Project name: ${PROJECT_NAME}"
 # -------------------------------------------------------------------------------------------------
 echo
 echo `date`
+echo "Before working with the beta site we will clear out the caches..."
+# -------------------------------------------------------------------------------------------------
+case "${PROJECT_TYPE}" in
+
+    drupal7|drupal6)
+	drush --root=/home/beta/projects/${PROJECT_NAME}/web cache-clear all
+        ;;
+
+    *)
+        echo "Error - Invalid project type."
+        exit 1
+esac
+
+# -------------------------------------------------------------------------------------------------
+echo
+echo `date`
 echo "Make backup copy of the beta site database..."
 # -------------------------------------------------------------------------------------------------
 mkdir -p /home/${USER}/backups/beta_sites
-mysqldump betapr${PROJECT_NAME} > /home/${USER}/backups/beta_sites/${PROJECT_NAME}_${DATE_TIME}.sql
+mysqldump betapr${PROJECT_NAME} > /home/${USER}/backups/beta_sites/${PROJECT_NAME}.sql
 ##tar --create --file=/home/${USER}/backups/beta_sites/${PROJECT_NAME}_${DATE_TIME}.tar /home/beta/projects/${PROJECT_NAME}/web
 
 # -------------------------------------------------------------------------------------------------
@@ -259,7 +282,7 @@ then
     __create_mysql_database_and_user_account ${DATABASE_NAME} ${DATABASE_USER} ${DATABASE_PASSWORD}
 
     echo "Loading the database from the beta database backup..."
-    mysql ${USER}pr${PROJECT_NAME} < /home/${USER}/backups/beta_sites/${PROJECT_NAME}_${DATE_TIME}.sql
+    mysql ${USER}pr${PROJECT_NAME} < /home/${USER}/backups/beta_sites/${PROJECT_NAME}.sql
 
     echo "Checking out the files from SVN to the new dev site..."
     svn checkout http://localhost/svn/${PROJECT_NAME} /home/${USER}/projects/${PROJECT_NAME}/web
@@ -399,9 +422,26 @@ else
     echo "Copy beta database on to dev..."
     mysqladmin --force drop ${USER}pr${PROJECT_NAME}
     mysqladmin create ${USER}pr${PROJECT_NAME}
-    mysql ${USER}pr${PROJECT_NAME} < /home/${USER}/backups/beta_sites/${PROJECT_NAME}_${DATE_TIME}.sql
+    mysql ${USER}pr${PROJECT_NAME} < /home/${USER}/backups/beta_sites/${PROJECT_NAME}.sql
 
 fi
+
+# -------------------------------------------------------------------------------------------------
+echo
+echo `date`
+echo "Here we will clear out caches - this avoids issues and keeps the sizes down..."
+# -------------------------------------------------------------------------------------------------
+case "${PROJECT_TYPE}" in
+
+    drupal7|drupal6)
+	drush --root=/home/beta/projects/${PROJECT_NAME}/web cache-clear all
+	drush --root=/home/${USER}/projects/${PROJECT_NAME}/web cache-clear all
+        ;;
+
+    *)
+        echo "Error - Invalid project type."
+        exit 1
+esac
 
 # -------------------------------------------------------------------------------------------------
 echo
@@ -417,4 +457,3 @@ echo "Finished - the developer copy of the site is at http://${USER}-pr-${PROJEC
 # -------------------------------------------------------------------------------------------------
 
 exit 0
-
diff --git a/pushdevtobeta b/pushdevtobeta
--- a/pushdevtobeta
+++ b/pushdevtobeta
@@ -1,19 +1,24 @@
 #!/bin/bash
 #===================================================================================
 #
-# FILE: pullinitialsitefromsource
+# FILE: pushdevtobeta
 #
-# USAGE: pullinitialsitefromsource [project type]
+# USAGE: pushdevtobeta [project type]
 #
-# DESCRIPTION: This will create an initial site which will be a vanilla copy from a
-# framework.  It will achieve this by pulling down any source code needed from 
-# repositories and creating any required databases.
+# DESCRIPTION: This will push the local dev copy up to the beta version.
 #
 # OPTIONS: see function ’usage’ below
 # NOTES: ---
 # AUTHOR: Kevin Bailey, kbailey@freewayprojects.com
 # COMPANY: Freeway Projects Limited
 #===================================================================================
+
+# Make sure only one Pullpush script is running at any one time.
+exec 9>/var/lock/pullpush
+if ! flock -n 9  ; then
+   echo "Another Pullpush script is currently running - try again later.";
+   exit 1
+fi
 
 # -------------------------------------------------------------------------------------------------
 # Set up global variables.
@@ -130,10 +135,6 @@ fi
 echo "All tests completed OK."
 echo "Project name: ${PROJECT_NAME}"
 
-
-
-
-
 # -------------------------------------------------------------------------------------------------
 echo
 echo `date`
@@ -163,8 +164,18 @@ echo "Changing permissions on the files/ directory to enable the script user to 
 # -------------------------------------------------------------------------------------------------
 echo
 echo `date`
-echo "Clearing out the caches on the sites to trim the database and files/ before copying and backing up..."
+echo "Clearing out the caches on the sites to trim the database and files/ before copying..."
 # -------------------------------------------------------------------------------------------------
+case "${PROJECT_TYPE}" in
+
+    drupal7|drupal6)
+	drush --root=/home/${USER}/projects/${PROJECT_NAME}/web cache-clear all
+        ;;
+
+    *)
+        echo "Error - Invalid project type."
+        exit 1
+esac
 
 # Bear in mind here that we may need to chmod the /files directory to 777 if we are not using Apache-ITK.
 ##drush @${DEV_SITE_NAME} cache-clear all
@@ -287,7 +298,6 @@ then
     sudo chmod -R 775 /home/beta/projects/${PROJECT_NAME}/web/sites/default/files
 fi
 
-
 # NB Now we need to chmod permissions on the files/ directory to enable the web server to manipulate
 # these files.
 ##sudo chmod -R 777 ${BETA_DOCUMENT_ROOT}/sites/default/files
@@ -317,6 +327,21 @@ echo "Here we will clear out the caches again - this is needed by some modules s
 
 ###drush --root=/home/${USER}/projects/${PROJECT_NAME} cache-clear all
 ###drush --root=/home/beta/web/${PROJECT_NAME} cache-clear all
+# -------------------------------------------------------------------------------------------------
+echo
+echo `date`
+echo "Clearing out the beta cache to clean it up..."
+# -------------------------------------------------------------------------------------------------
+case "${PROJECT_TYPE}" in
+
+    drupal7|drupal6)
+	drush --root=/home/beta/projects/${PROJECT_NAME}/web cache-clear all
+        ;;
+
+    *)
+        echo "Error - Invalid project type."
+        exit 1
+esac
 
 # -------------------------------------------------------------------------------------------------
 echo
diff --git a/pushinitialsitetobeta b/pushinitialsitetobeta
--- a/pushinitialsitetobeta
+++ b/pushinitialsitetobeta
@@ -13,6 +13,13 @@
 # COMPANY: Freeway Projects Limited
 #===================================================================================
 
+# Make sure only one Pullpush script is running at any one time.
+exec 9>/var/lock/pullpush
+if ! flock -n 9  ; then
+   echo "Another Pullpush script is currently running - try again later.";
+   exit 1
+fi
+
 # -------------------------------------------------------------------------------------------------
 # Set up global variables.
 #
@@ -163,8 +170,25 @@ echo `date`
 echo "Make backup copy of the initial site..."
 # -------------------------------------------------------------------------------------------------
 mkdir -p ~/backups/initial_sites
-sudo mysqldump ${USER}is${INITIAL_SITE_NAME} > /home/${USER}/backups/initial_sites/${USER}is${INITIAL_SITE_NAME}_${DATE_TIME}.sql
-tar --create --file=/home/${USER}/backups/initial_sites/${USER}is${INITIAL_SITE_NAME}_${DATE_TIME}.tar /home/${USER}/initial_sites/${INITIAL_SITE_NAME}/web
+##sudo mysqldump ${USER}is${INITIAL_SITE_NAME} > /home/${USER}/backups/initial_sites/${USER}is${INITIAL_SITE_NAME}_${DATE_TIME}.sql
+sudo mysqldump ${USER}is${INITIAL_SITE_NAME} > /home/${USER}/backups/initial_sites/${USER}is${INITIAL_SITE_NAME}.sql
+####tar --create --file=/home/${USER}/backups/initial_sites/${USER}is${INITIAL_SITE_NAME}_${DATE_TIME}.tar /home/${USER}/initial_sites/${INITIAL_SITE_NAME}/web
+
+# -------------------------------------------------------------------------------------------------
+echo
+echo `date`
+echo "For Drupal sites we should clear out the caches..."
+# -------------------------------------------------------------------------------------------------
+case "${PROJECT_TYPE}" in
+
+    drupal7|drupal6)
+	drush --root=/home/${USER}/initial_sites/${INITIAL_SITE_NAME}/web cache-clear all
+        ;;
+
+    *)
+        echo "Error - Invalid project type."
+        exit 1
+esac
 
 # -------------------------------------------------------------------------------------------------
 echo
@@ -177,7 +201,7 @@ DATABASE_USER=betapr${PROJECT_NAME}
 DATABASE_PASSWORD=`cat /dev/urandom | base64 | tr -d '[:punct:]' | tr -d '[:digit:]' | tr -d '[:upper:]' | cut -c1-10 | head -1`
 __create_mysql_database_and_user_account ${DATABASE_NAME} ${DATABASE_USER} ${DATABASE_PASSWORD}
 
-mysql betapr${PROJECT_NAME} < /home/${USER}/backups/initial_sites/${USER}is${INITIAL_SITE_NAME}_${DATE_TIME}.sql
+mysql betapr${PROJECT_NAME} < /home/${USER}/backups/initial_sites/${USER}is${INITIAL_SITE_NAME}.sql
 
 # -------------------------------------------------------------------------------------------------
 echo
@@ -191,7 +215,7 @@ sudo chown -R www-data:www-data /var/lib/svn/${PROJECT_NAME}
 
 # Here we will put a dump of the database into the code repository.  This means that the site can
 # be rebuilt from an export from the repository if needed.
-cp /home/${USER}/backups/initial_sites/${USER}is${INITIAL_SITE_NAME}_${DATE_TIME}.sql /home/${USER}/initial_sites/${INITIAL_SITE_NAME}/web/${USER}is${INITIAL_SITE_NAME}_${DATE_TIME}.sql
+####cp /home/${USER}/backups/initial_sites/${USER}is${INITIAL_SITE_NAME}_${DATE_TIME}.sql /home/${USER}/initial_sites/${INITIAL_SITE_NAME}/web/${USER}is${INITIAL_SITE_NAME}_${DATE_TIME}.sql
 
 svn import /home/${USER}/initial_sites/${INITIAL_SITE_NAME}/web http://localhost/svn/${PROJECT_NAME} -m "Initial import."
 
@@ -234,7 +258,7 @@ case "${PROJECT_TYPE}" in
 
     *)
         echo "Error - Invalid project type."
-        exit -1
+        exit 1
 esac
 
 # -------------------------------------------------------------------------------------------------
@@ -326,6 +350,24 @@ echo "Set up the beta vhost..."
 ##fi
 
 __set_up_vhost beta-pr-${PROJECT_NAME} /home/beta/projects/${PROJECT_NAME}/web
+
+
+# -------------------------------------------------------------------------------------------------
+echo
+echo `date`
+echo "To be tidy we will clear out the caches on the new beta site..."
+# -------------------------------------------------------------------------------------------------
+case "${PROJECT_TYPE}" in
+
+    drupal7|drupal6)
+	drush --root=/home/beta/projects/${PROJECT_NAME}/web cache-clear all
+        ;;
+
+    *)
+        echo "Error - Invalid project type."
+        exit 1
+esac
+
 
 
 # -------------------------------------------------------------------------------------------------
